#cloud-config
users:
  - name: automation-user
    ssh-authorized-keys:
      - <SHA256:fkmM8le7YkNCoG3+i+gQF3PW98RvhJS8IyTBhc0O22w>
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
packages:
  - curl
  - gnupg
  - software-properties-common
runcmd:
  - apt-get update
  - apt-add-repository --yes --update ppa:ansible/ansible
  - apt-get install -y ansible
  - curl -fsSL https://apt.releases.hashicorp.com/gpg | tee /etc/apt/trusted.gpg.d/hashicorp.gpg
  - apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
  - apt-get update
  - apt-get install -y terraform
